#! /bin/bash

awk 'NR % 9 == 2 { print $1 " " $3  " " $5 " " $7}' report1_mem1 >> first_line
awk 'NR % 9 == 3 { print $1 " " $3  " " $5 " " $7}' report1_mem1 >> second_line

awk 'NR % 9 == 5 { print $1 }' report1_mem1 >> top1
awk 'NR % 9 == 6 { print $1 }' report1_mem1 >> top2
awk 'NR % 9 == 7 { print $1 }' report1_mem1 >> top3
awk 'NR % 9 == 8 { print $1 }' report1_mem1 >> top4
awk 'NR % 9 == 0 { print $1 }' report1_mem1 >> top5
