#!/bin/bash
for pid in $(ps -A -o pid --no-header)
do
  file=/proc/$pid/io
  if [[ -f $file ]]
  then
    read_bytes=$(sudo grep read_bytes $file | grep -E -o '[[:digit:]]+')
    echo $pid $read_bytes >> temp1 
  fi
done
sudo rm answer7
echo "Sleeping for 60 sec..."
sleep 60
echo "Woke up"
while read string
do
  pid=$(echo $string | awk '{print $1}')
  old_read_bytes=$(echo $string | awk '{print $2}')
  file=/proc/$pid/io
  if [[ -f $file ]]
  then
    new_read_bytes=$(sudo grep read_bytes $file | grep -E -o '[[:digit:]]+')
    echo $pid $(echo $new_read_bytes $old_read_bytes | awk '{print $2-$1}') >> temp2
  fi
done < temp1
sudo sort -n -k2 temp2 > answer7
